name = "avatar-upload"
main = "src/index.ts"
compatibility_date = "2022-07-31"

node_compat = true

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = 'avatar-storage'
preview_bucket_name = 'preview-avatar-storage'