name = "avatar-upload"
main = "src/index.ts"
compatibility_date = "2023-05-18"

[vars]
BASE_WEB3_ENDPOINT = "https://web3.ens.domains/v1"
SUPPORTED_NETWORKS = ["mainnet", "goerli"]
REGISTRY_ADDRESS = "0x00000000000c2e074ec69a0dfb2997ba6c7d2e1e"
WRAPPER_ADDRESS = '{ "mainnet": "0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401", "goerli": "0x114D4603199df73e7D157787f8778E21fCd13066" }'
MULTICALL_ADDRESS = "0xcA11bde05977b3631167028862bE2a173976CA11"
BASE_REGISTRAR_ADDRESS = "0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85"

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = 'avatar-storage'
preview_bucket_name = 'preview-avatar-storage'