name: Deploy

on:
  release:
    types: [published]

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.8.0

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up git
        run: |
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'

      - name: Bump version to ${{ github.event.release.tag_name }}
        run: |
          pnpm version ${{ github.event.release.tag_name }} --no-git-tag-version

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiKey: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          env:
            WEB3_ENDPOINT: "https://web3.ens.domains/v1/mainnet"
            REGISTRY_ADDRESS: "0x00000000000c2e074ec69a0dfb2997ba6c7d2e1e"

      - name: Push changes
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
